services:
  app:
    image: ghcr.io/mazrean/web-speed-hackathon-2024-server:latest
    container_name: wsh2024-server
    expose:
      - 8000
    networks:
      - default
      - caddy-network
networks:
  caddy-network:
    name: caddy-network
