name: Deploy

on: 
  push:

env:
  IMAGE_NAME: web-speed-hackathon-2024
jobs:
  client-image:
    name: Build Client Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - uses: actions/checkout@v3.5.3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mazrean
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./deploy/client.Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/mazrean/${{ env.IMAGE_NAME }}-client:latest
            ghcr.io/mazrean/${{ env.IMAGE_NAME }}-client:${{ env.IMAGE_TAG }}
  server-image:
    name: Build Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - uses: actions/checkout@v3.5.3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mazrean
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./deploy/server.Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/mazrean/${{ env.IMAGE_NAME }}-server:latest
            ghcr.io/mazrean/${{ env.IMAGE_NAME }}-server:${{ env.IMAGE_TAG }}
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    environment: production
    needs: [server-image]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
      - uses: actions/checkout@v3.5.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mazrean
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Images
        env:
          DOCKER_HOST: ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
        # V2ではupでエラーが出るので、V1を使う ref:https://github.com/docker/compose/issues/8544
        run: docker-compose pull
        working-directory: ./deploy
      - name: Deploy
        env:
          DOCKER_HOST: ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
        # V2ではupでエラーが出るので、V1を使う ref:https://github.com/docker/compose/issues/8544
        run: docker-compose up -d
        working-directory: ./deploy
